### ISSUE TITLE
when i set a logo, there is an error

### ISSUE THREAD

**Issue by Leeying** [gera2ld/qrcanvas-vue#1]
use it in vue
options: {
        data: 'http://baidu.com', // 支付地址
        cellSize: 6, // 每个小格的像素宽度或者高度
        // size: 150, // 生成图片宽度或者高度，如有cellSize则此项被忽略
        // typeNumber: auto, // 如果太小将自动增加直到找到一个合适的 typeNumber
        // correctLevel: 'M', // 容错级别，如果指定了 logo 则设置为 H
        // colorDark: 'black', // 暗格的背景色
        // colorLight: 'white', // 亮格的背景色
        logo: {
          image: 'https://dn-coding-net-production-static.qbox.me/3963fc74-e74f-44f5-9bf3-988e68bd7b92.jpeg?imageMogr2/auto-orient/format/jpeg/crop/!450x450a338a0/thumbnail/80',
        },
      },

Uncaught (in promise) TypeError: Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The provided value is not of type '(HTMLImageElement or HTMLVideoElement or HTMLCanvasElement or ImageBitmap)'

**Comment by gera2ld** [comment]
`image` should be an `Image` or `Canvas` element.

```
var image = new Image;
image.onload = function () {
   options = Object.assign({}, options, logo: {image});
   // pass the new options object to the component
};
image.src = 'https://dn-coding-net-production-static.qbox.me/3963fc74-e74f-44f5-9bf3-988e68bd7b92.jpeg?imageMogr2/auto-orient/format/jpeg/crop/!450x450a338a0/thumbnail/80';
```
