### ISSUE TITLE
Padding does not show up

### ISSUE THREAD

**Issue by noahdeering** [gera2ld/qrcanvas-vue#10]
Using qrcanvas-vue 2.1.1 with Vue 2.6.10 and vuetify 2.2.19, padding does not show up around the QR Code. Adding a value to the 'padding' property just decreases the size of the QR Code.

**Comment by gera2ld** [comment]
I can confirm it works here: https://gera2ld.github.io/qrcanvas-vue/v2/#padding
Please provide a minimal reproduction if the issue persists.

**Comment by noahdeering** [comment]
It does appear to work in your demo; however, the real problem I am having is the background is transparent, so padding simply is empty space, not extra filled whitespace. Below is a screenshot of a generated QR Code with a padding of 34 on a background canvas, but as you can see the QR Code is transparent:

<img width="183" alt="Capture" src="https://user-images.githubusercontent.com/98047399/174321678-c6669f03-bb22-48d1-960b-c335e0cf2717.PNG">

I confirm the background is transparent by making the background of the surrounding div of the QR Code a dark color and seeing that no whitespace is added. Is there a way to make the background not transparent?

**Comment by gera2ld** [comment]
Are you using an old version of `qrcanvas`? The latest version (3.1.2) should have a default background of `white`, you can confirm that in the demo. Anyway you can pass `background: 'white'` to the options.
