### ISSUE TITLE
I found a error on Android 

### ISSUE THREAD

**Issue by pb-cheung** [gera2ld/qrcanvas-vue#2]
my template is:

```html
<qrcanvas v-bind:style="[{'width':qrcode_width}, {'height':qrcode_width}]" v-bind:options="qrcode_content" ></qrcanvas>
```
it works well on pc broswer, but when it comes to Android…… 
the error is：
![qrcode_error](https://cloud.githubusercontent.com/assets/5186428/20464273/e3c2187a-af7f-11e6-8e44-9e5469700fb4.png)

how to fix it?

**Comment by gera2ld** [comment]
`Object.assign` is not defined. I'll fix this soon. You may add a [polyfill](https://github.com/rubennorte/es6-object-assign) as a workaround first.
