### ISSUE TITLE
Vue.extend is not a function

### ISSUE THREAD

**Issue by mengkeys** [gera2ld/qrcanvas-vue#3]
![image](https://cloud.githubusercontent.com/assets/10555423/24053346/bafd8ce4-0b73-11e7-903f-09d1adf4fac0.png)

**Comment by gera2ld** [comment]
Please provide a minimal reproduction. Or at least the versions of your packages and webpack config.

**Comment by achuan9** [comment]
TypeError: Vue.extend is not a function

  "vue": "^2.0.1",
"qrcanvas-vue": "^1.0.1",

**Comment by novecento** [comment]
news about that? I'm in same condition with vuejs 3
"qrcanvas-vue": "^2.1.0"
