### ISSUE TITLE
vue2.0 ssr support ?

### ISSUE THREAD

**Issue by yanxileo** [gera2ld/qrcanvas-vue#4]
when I use vue ssr, throw an exception that `Cannot find module 'canvas'`, I know the question is from the `index.js` 
```javascript
render: function (createElement) {
    return createElement('canvas');
  }
```
how can I fixed it ?

**Comment by gera2ld** [comment]
You are definitely not supposed to create a canvas on the server side, right? Just check if it's the server side and only render it on client side, for example:
``` html
<qrcanvas v-if="isBrowser" :options="options"></qrcanvas>
```

**Comment by yanxileo** [comment]
@gera2ld  I know that, thx~
